name: deploy-container

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - 'container/**'

defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest
